### ISSUE TITLE
Updates to pypact analysis wiki 

### ISSUE THREAD

**Issue by RossWorrall** [fispact/pypact#18]
pypact.analysis has had attribute names changed, from getallisotopes() to get_all_isotopes(), and findZ() to find_z().

Wiki examples use old method names.

**Comment by thomasms** [comment]
Wiki or README? 
This certainly needs updating on the README, the example scripts in the 'examples' subdirectory should have already been updated.

**Comment by RossWorrall** [comment]
Just on the Wiki, I've not tried the example files. 

It's in the following section:

**Comment by RossWorrall** [comment]
Plotting
An example script and some helper functions are included to show how some plots can be constructed using pypact. A nuclide library (in JSON format) exists containing the list of all isotopes, that is containing 118 elements from H to Og, and totaling to 3352 isotopes. These can be used in their entirety as a complete list using 'getallisotopes()' or can be filtered as the example below shows. Some plotting functions are added in the 'pypact.analysis' module and are also used in the script below.

This example script is based on that in the package at 'pypact/examples/plotnuclideheat.py'. Note that this is an example only and is to show how pypact can be used to help perform certain analyses.

import re
import os

import pypact as pp
import pypact.analysis as ppa

filename = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             '..', 'reference', 'test127.out')

tz = ppa.TimeZone.COOL
properties = ['heat', 'grams', 'ingestion']
isotopes = [ ppa.NuclideDataEntry(i) for i in ppa.getallisotopes() if ppa.findZ(i[0]) <= 10]
