### ISSUE TITLE
fluxesfile.py: Writing fluxes files using setValue method doesn't set correct groups when small rounding errors present

### ISSUE THREAD

**Issue by rworrall-ukaea** [fispact/pypact#39]
Hi @thomasms,

I've had a problem when writing fluxes files, when small rounding errors are present the flux is written to the wrong group, with no error handling or warnings. 

I've come up with a fix, by adding a rounding tolerance: 

setValue(energy_group, flux_value, energy_group_tolerance=0.001

Example showing error:

`import pypact as pp

# writing a fluxes file
ff = pp.FluxesFile(name='test', norm=1.0)
ff.setGroup(175)
ff_boundaries = ff.boundaries[::-1]

ff.setValue(1.0000e-05, 1.0)
ff.setValue(1.0000e-01, 2.0)
ff.setValue(4.1400e-01, 3.0)
ff.setValue(5.3200e-01, 4.0)
ff.setValue(6.8300e-01, 5.0)

pp.to_file(ff, 'example.fluxes_file')

print(pp.ALL_GROUPS[175][-5:])`

Will result in a fluxes file with the 3rd 4th and 5th fluxes placed in the groups above, these are then overwritten by other values leaving gaps and incorrect values in the spectrum.

I've made a fix to this on a local branch, but can't push this. Could I be made a developer so that I can push the code to a fix branch?

Regards,

Ross

**Comment by thomasms** [comment]
We could add a tolerance, but I think that would defeat the purpose of that API. The `setValue` is intended as a convenience method for simple fluxes i.e setting a monoenergetic flux as:
```python
# will make a 14 MeV beam in 3 lines for 175 group
ff = pp.FluxesFile()
ff.setGroup(175)
ff.setValue(14.0e6, 1.0)

# to file
pp.to_file(ff, "fluxes")
```
or the other use case of `setValue` is to permute one or two bin values after setting a base spectrum i.e. doing total MC.
```python
ff = pp.FluxesFile()
ff.setGroup(175)
ff.values = [.....]
# change the 14 MeV bin to 0.8
ff.setValue(14.0e6, 0.8)

# to file
pp.to_file(ff, "fluxes")
```

If you simply just want to set a complete spectrum (all the bins) just use the values attribute.
For example:
```python
# an array of 175 values set or retrieved from somewhere else.
myvalues = [......]

ff = pp.FluxesFile()
ff.setGroup(175)
# values are not protected - can read & write
ff.values = myvalues

# to file
pp.to_file(ff, "fluxes")
```

Does this help with your use case?

**Comment by thomasms** [comment]
But if you still want to add the tolerance, then please make a pull request :)

**Comment by rworrall-ukaea** [comment]
Hi Tom, the values attribute works fine. 

Thanks,

Ross
