### ISSUE TITLE
Add convenience properties to Nuclide

### ISSUE THREAD

**Issue by thomasms** [fispact/pypact#40]
Would be nice to have
```python3
# nuclide is of Nuclide type
nuclide.zai
nuclide.name
```

Add as properties

**Comment by PeBoch** [comment]
Hi, when I run the coronaplot.py in outputplotting there is an AttributeError: 'Nuclide' object has no attribute name. I just thought to mention this here. Best regards.

Traceback (most recent call last):
File "coronaplot.py", line 111, in <module>
mat, nuclides, times, min_value, max_value = make_mat (output, prop-PROP, ax=ax) File "coronaplot.py", line 66, in make_mat
nuclides = sorted_top_nuclides (output, ntop=TOP_NUCLIDES, prop=prop) File "coronaplot.py", line 93, in sorted_top_nuclides I
name = nuclide.name
AttributeError: 'Nuclide' object has no attribute 'name'

**Comment by thomasms** [comment]
Hi, I don't see this on master (works as below).
![image](https://user-images.githubusercontent.com/8820266/192851502-e90559d4-1a11-40eb-aaef-b63d87f81cd3.png)

But you're correct that this does not work with the latest version on pypi (via `pip install pypact`), so this need updating. I will update the version and check this works. Thanks for reporting this.

**Comment by thomasms** [comment]
This should be fixed in 1.3.6, if you do: `pip install --upgrade pypact` and try again does it work now?

**Comment by PeBoch** [comment]
I've just tested it after upgrading to pypact 1.3.6. It works like a charm now. Thanks for your super fast reply!

**Comment by thomasms** [comment]
Glad it works for you. Thanks for catching this issue!
