### ISSUE TITLE
install fails on v1.3.5 from pypi

### ISSUE THREAD

**Issue by dvp2015** [fispact/pypact#43]
Installation fails because the file ".VERSION" is missed in the pypact-1.3.5.tar.gz archive from PyPI. 
This prevents using pypact-1.3.5 as dependency from PyPI.

![image](https://user-images.githubusercontent.com/10807799/121546609-1840f900-ca14-11eb-9029-1c0a8b3ecb45.png)

**Comment by thomasms** [comment]
Your fix seems to have worked.

![image](https://user-images.githubusercontent.com/8820266/121586735-46cecc00-ca34-11eb-82a6-daebba026722.png)

But please confirm. I also updated this on pypi.
