### ISSUE TITLE
'LinePlotAdapter' object has not attribute 'custom'

### ISSUE THREAD

**Issue by PeBoch** [fispact/pypact#46]
Hi,
I think I noted a bug when running the plotnuclideheat.py with ppa.TimeZone.BOTH (irradiation and decay) resulting in an AttributeError: 'LinePlotAdapter' object has not attribute 'custom'. Checking in plotadapter.py in the LinePlotAdapter class there is indeed no attribute 'custom'.
For now, i just comment out the lines and the script works.
Regards, Peter.

**Comment by PeBoch** [comment]
I added to plotadapter.py to class LinePlotAdapter the following attribute

def custom (self, x, **kwargs):
      self.engine.axvline(x, **kwargs)

Which draws that vertical line as it seems to have been foreseen by your code initially

Example figure from plotnuclideheat.py with TimeZone.BOTH
![example](https://user-images.githubusercontent.com/17641298/194574408-32f24837-0dda-4a1c-9ad6-1e7bac6842db.jpeg)

**Comment by thomasms** [comment]
Thanks for catching this. Indeed it is a bug - `custom` is not in the interface for the plotter.
For me, I had to add this:
![image](https://user-images.githubusercontent.com/8820266/194637134-f03cc95a-7d4c-4361-b763-2b3018f70a2a.png)

Feel free to open a PR to fix this.
